(function(){
  'use strict';
  const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));

  // Theme
  const themeToggle=$('#themeToggle');
  function currentTheme(){const t=document.documentElement.getAttribute('data-theme');if(t)return t;return window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'}
  function syncThemeLabel(){if(themeToggle)themeToggle.setAttribute('aria-label','Switch to '+(currentTheme()==='dark'?'light':'dark')+' theme')}
  if(themeToggle){syncThemeLabel();themeToggle.addEventListener('click',()=>{const next=currentTheme()==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',next);try{localStorage.setItem('ct-theme',next)}catch(e){}syncThemeLabel()})}

  // Mobile nav
  const mobileToggle=$('#mobileToggle'),mobileNav=$('#mobileNav');
  function closeMobile(){if(!mobileNav||!mobileToggle)return;mobileNav.classList.remove('open');mobileToggle.setAttribute('aria-expanded','false')}
  if(mobileToggle&&mobileNav){mobileToggle.addEventListener('click',()=>{const open=mobileNav.classList.toggle('open');mobileToggle.setAttribute('aria-expanded',open?'true':'false')});mobileNav.addEventListener('click',e=>{if(e.target.closest('a'))closeMobile()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMobile()})}

  // Top tabs active state
  const topLinks=$$('.topTabs a');
  const sections=['system','toolsHub','resources'];
  if('IntersectionObserver' in window){const obs=new IntersectionObserver(entries=>{entries.forEach(en=>{if(en.isIntersecting){topLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+en.target.id))}})},{rootMargin:'-30% 0px -55% 0px'});sections.forEach(id=>{const el=document.getElementById(id);if(el)obs.observe(el)})}

  // Decision tool tabs
  const toolTabs=$$('.toolTab'),toolPanels=$$('.toolPanel');
  function openTool(id){toolTabs.forEach(b=>b.classList.toggle('active',b.dataset.tool===id));toolPanels.forEach(p=>p.classList.toggle('active',p.id===id))}
  toolTabs.forEach(b=>b.addEventListener('click',()=>openTool(b.dataset.tool)));
  ['govTool','feedTool','scaleTool'].forEach(id=>document.querySelectorAll('a[href="#'+id+'"]').forEach(a=>a.addEventListener('click',()=>openTool(id))));

  // Governance selector
  const modelCopy={
    ulb:{title:'Publicly owned and operated',lead:'Best fit where the public entity controls assets and collection and has strong day-to-day operating capability.',watch:'Administrative delays can weaken maintenance, staffing and market decisions.',clarify:['Operating staffing and specialist roles','Material-sale authority and revenue retention','Maintenance budget and procurement speed','Performance accountability inside the public system']},
    om:{title:'Public asset + private O&M',lead:'Best fit where the public side owns infrastructure and feedstock while a specialist operator runs daily operations against service standards.',watch:'The operator should not be held accountable for feedstock quality or tonnage it cannot control.',clarify:['Feedstock and minimum-service commitments','Service fee and performance-linked payment logic','Material revenue and residue-cost ownership','KPIs, escalation and handback conditions']},
    concession:{title:'Performance-linked concession',lead:'Best fit where private capability and capital can be combined with public feedstock, land or service rights over a defined contract period.',watch:'Risk transfer fails when the operator carries market, tonnage and payment risks without corresponding control.',clarify:['Capital obligations and asset ownership at term end','Tonnage / collection commitments','Revenue stack and market-risk allocation','Contract duration and termination logic']},
    private:{title:'Privately financed and operated',lead:'Best fit where the operator can secure feedstock, finance infrastructure, manage markets and operate with limited dependence on public systems.',watch:'Feedstock access and land tenure must be durable, not informal or short term.',clarify:['Long-term feedstock rights','Land / facility tenure','Authorised downstream channels','Exposure to price and volume volatility']},
    coop:{title:'Cooperative / worker-led',lead:'Best fit where worker ownership, livelihoods and local collection relationships are central to the model and commercial capability can be built around them.',watch:'Social ownership still requires strong technical management, financial controls and market discipline.',clarify:['Governance and management roles','Commercial decision rights','Working capital and buyer relationships','Training, equipment and professional support']},
    hybrid:{title:'Hybrid partnership model',lead:'Best fit where ownership, capital, collection and operating capability need to be shared across public, private and community actors.',watch:'Shared responsibility must still translate into one accountable owner for every function.',clarify:['One accountable owner for each system function','Collection-processing interfaces','Revenue, cost and risk allocation','Decision rights when partners disagree']}
  };
  const weights={assets:{public:{ulb:3,om:3,concession:2,hybrid:2},private:{private:3,concession:2},community:{coop:4,hybrid:2},shared:{hybrid:4,concession:2}},collection:{public:{ulb:2,om:3},operator:{private:3,concession:3},community:{coop:4,hybrid:2},shared:{hybrid:4,om:1}},capex:{public:{ulb:2,om:3},private:{private:3,concession:4},shared:{hybrid:4,concession:2}},capacity:{strong:{ulb:4},moderate:{om:3,hybrid:3},limited:{concession:3,private:2,om:2}},market:{operator:{private:3,concession:3},public:{ulb:2},shared:{hybrid:4}},inclusion:{core:{coop:5,hybrid:3},integrated:{hybrid:3,om:1,concession:1},standard:{ulb:1,om:1,concession:1,private:1}}};
  const govForm=$('#govForm');if(govForm)govForm.addEventListener('submit',e=>{e.preventDefault();const vals={assets:$('#govAssets').value,collection:$('#govCollection').value,capex:$('#govCapex').value,capacity:$('#govCapacity').value,market:$('#govMarket').value,inclusion:$('#govInclusion').value};if(Object.values(vals).some(v=>!v)){renderEmpty('#govResult','Complete all six questions','The model selector needs the full operating context.');return}const score={ulb:0,om:0,concession:0,private:0,coop:0,hybrid:0};Object.keys(vals).forEach(k=>Object.entries(weights[k][vals[k]]||{}).forEach(([m,s])=>score[m]+=s));const ranked=Object.entries(score).sort((a,b)=>b[1]-a[1]),best=modelCopy[ranked[0][0]],second=modelCopy[ranked[1][0]];$('#govResult').innerHTML=`<span class="resultBadge good">Recommended starting architecture</span><h3 class="resultTitle">${best.title}</h3><p>${best.lead}</p><div class="resultGrid"><div class="resultBox"><b>Clarify before contracting</b><ul>${best.clarify.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="resultBox"><b>Main watch-out</b><ul><li>${best.watch}</li><li>Alternative worth testing: ${second.title}</li></ul></div></div><div class="resultMeta">Decision aid only · procurement, legal structure and approvals require context-specific review</div>`});
  const govReset=$('#govReset');if(govReset)govReset.addEventListener('click',()=>{govForm.reset();renderEmpty('#govResult','Describe the operating context','The selector will recommend a best-fit governance model and key issues to resolve.')});

  // Feedstock grader
  const feedForm=$('#feedForm');if(feedForm)feedForm.addEventListener('submit',e=>{e.preventDefault();const seg=$('#feedSeg').value,cont=$('#feedContam').value,moist=$('#feedMoisture').value,special=$('#feedSpecial').value,bulky=$('#feedBulky').value;if(!seg||cont===''||!moist||!special||!bulky){renderEmpty('#feedResult','Complete the intake observations','The grader needs all five quality observations.');return}const n=Math.max(0,Math.min(100,Number(cont)));let grade='A';if(special==='present'||seg==='mixed'||moist==='wet'||n>25||bulky==='significant')grade='C';else if(special==='suspected'||seg==='mostly'||moist==='damp'||n>5||bulky==='manageable')grade='B';const action=grade==='A'?'Accept — standard sorting':grade==='B'?'Conditional accept — pre-sort required':'Quarantine / reject from normal dry line';const reasons=[];if(seg==='mixed')reasons.push('The load is not a distinct dry-waste stream');if(n>25)reasons.push('Visible contamination is above the toolkit C-grade trigger');else if(n>5)reasons.push('Visible contamination is above the toolkit A-grade trigger');if(moist==='wet')reasons.push('Wet / putrescible contamination is present');else if(moist==='damp')reasons.push('Moisture may reduce material quality and value');if(special==='present')reasons.push('Special-care / hazardous items are clearly present');else if(special==='suspected')reasons.push('Special-care items require isolation and verification');if(bulky==='significant')reasons.push('Bulky material obstructs the normal line');else if(bulky==='manageable')reasons.push('Pre-sort is needed for bulky material');if(!reasons.length)reasons.push('The load appears clean, dry and compatible with the normal line');const handling=grade==='A'?['Accept into the standard dry-waste flow','Record source, weight and grade','Maintain normal visual QC']:grade==='B'?['Conditionally accept if the site SOP allows','Pre-sort before the normal line','Record the downgrade reason against the source']:['Do not send directly into the normal dry-waste line','Quarantine or isolate the affected fraction','Escalate persistent non-conformance upstream'];$('#feedResult').innerHTML=`<span class="resultBadge ${grade==='A'?'good':grade==='B'?'watch':'risk'}">Grade ${grade}</span><h3 class="resultTitle">${action}</h3><p>${reasons[0]}.</p><div class="resultGrid"><div class="resultBox"><b>Why this grade</b><ul>${reasons.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="resultBox"><b>Handling action</b><ul>${handling.map(x=>`<li>${x}</li>`).join('')}</ul></div></div><div class="resultMeta">A/B/C cut-offs are toolkit heuristics · site SOPs and applicable waste-stream rules take precedence</div>`});
  const feedReset=$('#feedReset');if(feedReset)feedReset.addEventListener('click',()=>{feedForm.reset();renderEmpty('#feedResult','Assess an incoming load','The grader returns an intake grade, handling action and reason.')});

  // Scale readiness
  const scaleForm=$('#scaleForm');const routeCopy={feedstock:'Expand feedstock and catchment',capacity:'Add processing capacity',value:'Move up the material-value curve',services:'Add service and traceability layers',geography:'Replicate into a new geography',unsure:'Clarify the scale thesis before committing capital'};if(scaleForm)scaleForm.addEventListener('submit',e=>{e.preventDefault();const ids=['scalePerformance','scaleFeedstock','scaleMarkets','scaleSystems','scalePeople','scaleFinance','scaleCompliance'];const vals=ids.map(id=>$('#'+id).value),opp=$('#scaleOpportunity').value;if(vals.some(v=>v==='')||!opp){renderEmpty('#scaleResult','Complete all readiness dimensions','One weak gate can change the scale recommendation.');return}const score=vals.reduce((a,v)=>a+Number(v),0),pct=Math.round(score/14*100),hardNo=['scalePerformance','scaleMarkets','scaleCompliance'].filter(id=>$('#'+id).value==='0');let status='Strengthen the base before scaling',cls='risk';if(score>=12&&!hardNo.length){status='Ready to scale';cls='good'}else if(score>=8&&!hardNo.length){status='Scale with conditions';cls='watch'}else if(score>=10&&hardNo.length){status='Fix gating conditions before scaling';cls='risk'}const gaps=ids.filter(id=>Number($('#'+id).value)<2).map(id=>$('#'+id).dataset.label+' — '+(Number($('#'+id).value)===0?'not in place':'partly in place'));$('#scaleResult').innerHTML=`<span class="resultBadge ${cls}">${score} / 14 · ${pct}%</span><h3 class="resultTitle">${status}</h3><p>Strongest stated route: <strong>${routeCopy[opp]}</strong>.</p><div class="resultGrid"><div class="resultBox"><b>Gaps to close</b><ul>${(gaps.length?gaps:['No material readiness gaps from the answers provided']).map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="resultBox"><b>Next action</b><ul><li>${cls==='good'?'Build a scoped scale case with explicit volume, economics, owners and milestones.':cls==='watch'?'Close partial gaps in parallel with a limited scale pilot.':'Do not add major fixed capacity or geographic complexity until the gating gaps are closed.'}</li></ul></div></div><div class="resultMeta">Readiness scoring is a toolkit heuristic · use verified operating data before committing investment</div>`});
  const scaleReset=$('#scaleReset');if(scaleReset)scaleReset.addEventListener('click',()=>{scaleForm.reset();renderEmpty('#scaleResult','Test the base before adding complexity','The diagnostic will show readiness, gating gaps and the stated growth route.')});

  // Health diagnostic
  const healthMetrics=[['hcUtil','Capacity utilisation',v=>v>=70&&v<=90,v=>v>=50&&v<70],['hcRecovery','Recovery efficiency',v=>v>=60,v=>v>=40],['hcBuyers','Buyer diversity',v=>v>=3,v=>v===2],['hcLabour','Labour productivity',v=>v>=250,v=>v>=150],['hcInventory','Inventory days',v=>v<15,v=>v<=30],['hcCost','Cost per kg recovered',v=>v<=5,v=>v<=8]];
  const healthForm=$('#healthForm');function assessHealth(){const items=[];healthMetrics.forEach(([id,label,good,watch])=>{const raw=$('#'+id).value;if(raw==='')return;const v=Number(raw),zone=good(v)?'good':watch(v)?'watch':'risk';items.push({label,v,zone})});if(!items.length){$('#healthResults').innerHTML='<div class="resultEmpty"><div><strong>Enter one or more values</strong><span>The diagnostic will show performance zones.</span></div></div>';return}$('#healthResults').innerHTML=`<div class="healthGrid">${items.map(i=>`<div class="healthItem"><b>${i.label}</b><small>Entered value: ${i.v}</small><span class="resultBadge ${i.zone}">${i.zone==='good'?'On track':i.zone==='watch'?'Needs attention':'Act now'}</span></div>`).join('')}</div>`}if(healthForm){healthForm.addEventListener('submit',e=>{e.preventDefault();assessHealth()});healthMetrics.forEach(([id])=>$('#'+id).addEventListener('input',assessHealth));$('#healthReset').addEventListener('click',()=>{healthForm.reset();assessHealth()})}

  // Planner
  const defaults={population:250000,wastePerCapita:.55,dryShare:30,collectionEfficiency:80,captureRate:85,recoveryRate:78,daysPerMonth:26,realization:6500,serviceFee:1200,opex:4200};
  const fmt=n=>Math.round(n).toLocaleString('en-IN'),money=n=>{const a=Math.abs(n),s=n<0?'-':'';return a>=1e7?s+'₹'+(a/1e7).toFixed(1)+' Cr':a>=1e5?s+'₹'+(a/1e5).toFixed(1)+' L':s+'₹'+fmt(a)};
  function planner(){const v=id=>Number($('#'+id).value)||0,p=id=>v(id)/100;const waste=v('population')*v('wastePerCapita')/1000,dry=waste*p('dryShare'),inb=dry*p('collectionEfficiency')*p('captureRate'),month=inb*v('daysPerMonth'),rec=month*p('recoveryRate'),res=month-rec,ann=rec*12;let footFactor=1200,lineCap=5,basePeople=8,peopleRate=2;if(inb>5&&inb<=15){footFactor=1000;lineCap=8;basePeople=12;peopleRate=1.8}else if(inb>15){footFactor=900;lineCap=10;basePeople=18;peopleRate=1.5}const foot=Math.max(2500,inb*footFactor),lines=Math.max(1,Math.ceil(inb/lineCap)),people=Math.max(basePeople,Math.round(basePeople+inb*peopleRate)),mat=rec*v('realization'),srv=month*v('serviceFee'),cost=month*v('opex'),margin=mat+srv-cost;$('#plannerCapacity').textContent=inb.toFixed(1)+' TPD';$('#plannerStatus').textContent=margin>=0?'Indicatively viable':'Viability gap';$('#plannerStatus').className='resultBadge '+(margin>=0?'good':'watch');const pairs={plannerRecovered:fmt(rec)+' t/mo',plannerResidual:fmt(res)+' t/mo',plannerAnnual:fmt(ann)+' t/yr',plannerFootprint:fmt(foot)+' sq ft',plannerLines:lines,plannerPeople:people,plannerMaterial:money(mat),plannerService:money(srv),plannerCost:money(cost),plannerMargin:money(margin)};Object.entries(pairs).forEach(([id,val])=>$('#'+id).textContent=val);return{inb,rec,res,ann,foot,lines,people,mat,srv,cost,margin}}
  const plannerForm=$('#plannerForm');if(plannerForm){plannerForm.addEventListener('input',planner);plannerForm.addEventListener('submit',e=>{e.preventDefault();planner()});$('#plannerReset').addEventListener('click',()=>{Object.entries(defaults).forEach(([id,val])=>$('#'+id).value=val);planner()});planner()}
  $('#plannerPrint')?.addEventListener('click',()=>window.print());$('#plannerCopy')?.addEventListener('click',async()=>{const r=planner();const text=`Circularity Toolkit — Recovery System Planner\nRequired inbound capacity: ${r.inb.toFixed(1)} TPD\nRecovered material: ${fmt(r.rec)} t/month\nAnnual diversion: ${fmt(r.ann)} t/year\nIndicative footprint: ${fmt(r.foot)} sq ft\nOperating margin: ${money(r.margin)}\nOutputs are directional and require technical validation.`;try{await navigator.clipboard.writeText(text);$('#plannerCopy').textContent='Copied';setTimeout(()=>$('#plannerCopy').textContent='Copy summary',1600)}catch(e){}});$('#plannerCsv')?.addEventListener('click',()=>{const r=planner();const csv='Item,Value\nRequired inbound capacity,'+r.inb.toFixed(1)+' TPD\nRecovered material,'+fmt(r.rec)+' t/month\nResiduals,'+fmt(r.res)+' t/month\nAnnual diversion,'+fmt(r.ann)+' t/year\nIndicative footprint,'+fmt(r.foot)+' sq ft\nSorting lines,'+r.lines+'\nPeople per shift,'+r.people+'\nOperating margin,'+money(r.margin);const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='circularity-planner.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),600)});

  // Module expand all
  $('#expandModules')?.addEventListener('click',e=>{const open=e.currentTarget.dataset.open!=='true';$$('.modules details').forEach(d=>d.open=open);e.currentTarget.dataset.open=open?'true':'false';e.currentTarget.textContent=open?'Collapse modules':'Expand all modules'});

  // Resource downloads
  $$('[data-download]').forEach(btn=>btn.addEventListener('click',async()=>{if(!window.CTDownloads){alert('Download engine is still loading. Please try again.');return}const key=btn.dataset.download;const old=btn.textContent;btn.disabled=true;btn.textContent='Preparing…';try{await window.CTDownloads[key]()}finally{btn.disabled=false;btn.textContent=old}}));

  function renderEmpty(sel,title,text){const el=$(sel);if(el)el.innerHTML=`<div class="resultEmpty"><div><strong>${title}</strong><span>${text}</span></div></div>`}
})();
